## Lists, Dictionaries and Sets in Python

## Part 1

### Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [3]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]
print(l1)

['learning', 'Python', 'is fun?', True]

List can also be created by using list() function.

In [4]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]

Adding to an existing list

### Question 1

Add 10 to list l1 given above.

[ **Hint: ** Use **append** ]

In [5]:
l1.append('10')
print (l1)

['learning', 'Python', 'is fun?', True, '10']

Removing from an existing list

### Question 2

Remove 10 from l1.

[ **Hint:** Use **remove**]

In [6]:
l1.remove('10')
print (l1)

['learning', 'Python', 'is fun?', True]

Joining 2 lists

### Question 3

[ **Hint: ** Use **+** operator or **extend**]

In [25]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))

In [7]:
l3=l1+l2
print (l3)

['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]

In [8]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))
l1.extend(l2)
print(l1)

['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]

Number List

### Question 4

Find Range and Mean of l3.

l3 = [2,4,6,8]

[ **Hint: ** Use **len(),sum(), min(), max()** functions ]
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [26]:
l3 = [2,4,6,8]
x= sum(l3)
y=(len(l3))
Mean =x/y
Range=max(l3)-min(l3)
print("Range =" ,Range)
print("Mean =", Mean)

Range = 6
Mean = 5.0

Count the occurances of an element in a given list.

### Question 5
Append the given sequence of numbers to l3 (given above) 0,1,3,3,5,5,7,9. Count the occurences of 5 in l3.

[ **Hint: ** Use ** + operator to add multiple elements in the array and count() function to print the occurences**]

In [27]:
l3 = [2,4,6,8]
x =[0,1,3,3,5,5,7,9]
l3.extend(x)
print(l3)

[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]

Sorting and Reversing a list

### Question 6
sort and print l3 in ascending and descending order sequentially (given above)

**(Hint: Use .sort() function)**

In [28]:
l3.sort()
print(l3)

[0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]

In [31]:
l3.sort(reverse = True)
print(l3)

[9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]

### Functions

**Example:**

**def** function_name(args)**:**
    
    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [32]:
def sum_3(x,y,z):
    return x+y+z
a=int(input())
b=int(input())
c=int(input())
print("Sum of Number equal ",sum_3(a,b,c))

 1
 4
 5

Sum of Number equal  10

### Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2

### Question 8

Write the same above **sum_3** function using lambda.

In [34]:
x= lambda a,b,c:a+b+c
print(x(5,4,6))

15

# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.

In [18]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [19]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]

Sum functions on np.array()

In [20]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2L, 4L)
8
int32

### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [4]:
import numpy as np
A3=np.identity(3)
print(A3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function

In [5]:
A4=np.matrix([[9,8,7],[6,5,4],[3,2,1]])
print(A4)

[[9 8 7]
 [6 5 4]
 [3 2 1]]

### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [6]:

A5=np.transpose(A4)
print(A5)

[[9 6 3]
 [8 5 2]
 [7 4 1]]

### Question 4
Add + 1 to all the elements in the given matrix.

In [7]:
A6=A5+1
print(A6)

[[10  7  4]
 [ 9  6  3]
 [ 8  5  2]]

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function

In [10]:
nd6 = [[ 1, 4 ,9 ,121 ,144 ,169], [ 16 ,25 ,36, 196 ,225 ,256], [ 49, 64 ,81 ,289 ,324 ,361]]
mean=np.mean(nd6)
print(mean)

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

# Pandas

We have seen Numpy in the last section. It is good at performing math operation on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](http://pandas.pydata.org/pandas-docs/version/0.23/dsintro.html)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [2]:
import numpy as np
import pandas as pd

In [3]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

[**Hint:** Use **.Series**]

In [1]:
d1 = {'a': 1, 'b': 2, 'c': 3}

In [2]:
import pandas as pd
d2= pd.Series(d1)
print(d2)

a    1
b    2
c    3
dtype: int64

You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


[ **Hint: ** Use **np.dot()** ]

## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column.

In [4]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':['x','y','z'] }
df1 = pd.DataFrame(d1)
df1

   a  b  c
0  1  3  x
1  2  4  y
2  3  5  z

### Question 3

Select second row in the above dataframe df1.

In [9]:
df2=df1.iloc[:,1]
print(df2)

0    3
1    4
2    5
Name: b, dtype: int64

### Question 4

Select column c in second row of df1.

[ **Hint: ** For using labels use **df.loc[row, column]**. For using numeric indexed use **df.iloc[]**. For using mixture of numeric indexes and labels use **df.ix[row, column]** ]

In [13]:
df3=df1.iloc[2,:]
print(df3)

a    3
b    5
c    z
Name: 2, dtype: object

## Using Dataframes on a dataset

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors

In [3]:
## Reading a dataset from a csv file using pandas.
import pandas as pd
mtcars = pd.read_csv('mtcars.csv')
mtcars.index = mtcars['name']

Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


[ **Hint: ** Use **type()** and **df.shape** ]

In [4]:
print(mtcars.info())
print(mtcars.shape)

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 12 columns):
name    32 non-null object
mpg     32 non-null float64
cyl     32 non-null int64
disp    32 non-null float64
hp      32 non-null int64
drat    32 non-null float64
wt      32 non-null float64
qsec    32 non-null float64
vs      32 non-null int64
am      32 non-null int64
gear    32 non-null int64
carb    32 non-null int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.2+ KB
None
(32, 12)

### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

[**Hint:** Use **.head()** and **.tail()**]

In [6]:
print(mtcars.head(10))

                                name   mpg  cyl   disp   hp  drat     wt  \
name
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440
Valiant                      Valiant  18.1    6  225.0  105  2.76  3.460
Duster 360                Duster 360  14.3    8  360.0  245  3.21  3.570
Merc 240D                  Merc 240D  24.4    4  146.7   62  3.69  3.190
Merc 230                    Merc 230  22.8    4  140.8   95  3.92  3.150
Merc 280                    Merc 280  19.2    6  167.6  123  3.92  3.440

                    qsec  vs  am  gear  carb
name
Mazda RX4          16.46   0   1     4     4
Mazda RX4 Wag      17.02   0   1     4     4
Datsun 710         18.61   1   1     4     1
Hornet 4 Drive     19.44   1   0     3     1
Hornet Sportabout  17.02   0   0     3     2
Valiant            20.22   1   0     3     1
Duster 360         15.84   0   0     3     4
Merc 240D          20.00   1   0     4     2
Merc 230           22.90   1   0     4     2
Merc 280           18.30   1   0     4     4

In [7]:
print(mtcars.tail(10))

                              name   mpg  cyl   disp   hp  drat     wt   qsec  \
name
AMC Javelin            AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30
Camaro Z28              Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41
Pontiac Firebird  Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05
Fiat X1-9                Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90
Porsche 914-2        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70
Lotus Europa          Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90
Ford Pantera L      Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50
Ferrari Dino          Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50
Maserati Bora        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60
Volvo 142E              Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60

                  vs  am  gear  carb
name
AMC Javelin        0   0     3     2
Camaro Z28         0   0     3     4
Pontiac Firebird   0   0     3     2
Fiat X1-9          1   1     4     1
Porsche 914-2      0   1     5     2
Lotus Europa       1   1     5     2
Ford Pantera L     0   1     5     4
Ferrari Dino       0   1     5     6
Maserati Bora      0   1     5     8
Volvo 142E         1   1     4     2

### Question 7

Print all the column labels in the given dataset - mtcars.

[ **Hint: ** Use **df.columns** ]

In [16]:
print(mtcars.columns)

Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

### Question 8

In [25]:
print(mtcars.iloc[[0,1,2,3,4,5],[1,2]])

                    mpg  cyl
name
Mazda RX4          21.0    6
Mazda RX4 Wag      21.0    6
Datsun 710         22.8    4
Hornet 4 Drive     21.4    6
Hornet Sportabout  18.7    8
Valiant            18.1    6

Select first 6 rows and 3 columns in mtcars dataframe.

**Hint: **  
mtcars.ix[:,:] gives all rows and columns in the dataset.

## Lab Brief - Statistical Learning with Python

### Part-1

## Measures of Data

Descriptive Statistcs are measures that summarize important features of data. Producing these descriptive statistics is a common first step to take after cleaning and preparing a dataset for further analysis. Examples are like calculating Mean or Median. In this lab, we will be looking into some of these functions and explore several new ones.

#### Measures of Central Tendency

Whenever you measure things of the same kind, a fairly large number of such measurements will tend to cluster around the middle value. Such a value is called a measure of "Central Tendency". The other terms that are used synonymously are "Measures of Location", or "Statistical Averages".

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

mtcars = pd.read_csv('mtcars.csv')

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors

#### Explore the data - Setting the index

In [3]:
mtcars.index = mtcars["name"]
mtcars.head()
# mtcars.mean() #By default this will give the mean of each column

,name,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
name,,,,,,,,,,,,
Mazda RX4,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

### Question 1

What is the first car name given in mtcars?

** Make use of index which has been set previously **

**Hint**: Use .loc function

In [75]:
print(mtcars.iloc[1],[0])

name    Mazda RX4 Wag
mpg                21
cyl                 6
disp              160
hp                110
drat              3.9
wt              2.875
qsec            17.02
vs                  0
am                  1
gear                4
carb                4
Name: Mazda RX4 Wag, dtype: object [0]

### Question 2
What is the highest difference between the hp and cyl?

**Hint:** You can use **max()** function to find the difference

In [72]:
mtcars1=pd.DataFrame(mtcars)
mtcars1
df8=(mtcars1["hp"].max()-mtcars1["cyl"].max())
print(df8)

327

### Question 3
What are the cars having highest weight(wt) and lowest weight(wt)?

**Hint:** Use idxmax() and idxmin() to locate the row

Use **.iloc** function to print the  row

**Note:** Both idxmax and idxmin belong to pandas

### Question 4

Find the mean of each row and each column in the given dataset.

**Hint:** Use .mean() function. To operate on rows use **axis=0**, on columns use **axis=1**

In [95]:
print("Rows mean\n",mtcars.mean(1))
print("Columns mean\n",mtcars.mean(0))

Rows mean
 name
Mazda RX4              29.907273
Mazda RX4 Wag          29.981364
Datsun 710             23.598182
Hornet 4 Drive         38.739545
Hornet Sportabout      53.664545
Valiant                35.049091
Duster 360             59.720000
Merc 240D              24.634545
Merc 230               27.233636
Merc 280               31.860000
Merc 280C              31.787273
Merc 450SE             46.430909
Merc 450SL             46.500000
Merc 450SLC            46.350000
Cadillac Fleetwood     66.232727
Lincoln Continental    66.058545
Chrysler Imperial      65.972273
Fiat 128               19.440909
Honda Civic            17.742273
Toyota Corolla         18.814091
Toyota Corona          24.888636
Dodge Challenger       47.240909
AMC Javelin            46.007727
Camaro Z28             58.752727
Pontiac Firebird       57.379545
Fiat X1-9              18.928636
Porsche 914-2          24.779091
Lotus Europa           24.880273
Ford Pantera L         60.971818
Ferrari Dino           34.508182
Maserati Bora          63.155455
Volvo 142E             26.262727
dtype: float64
Columns mean
 mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

### Question 5

Plot mpg values of mtcards dataframe using matplotlib.

**Hint: Use plt.plot function**

## Part 2

## Measures of Dispersion

Measures of Dispersion (Spread) are statistics that describe how data varies. Measure of dispersion gives us the sense of how much the data tends to diverge from the central tendency.

### Question 6

What the range of `mpg` in the given dataset?

**Hint:** Range = max-min

In [86]:
Range=(mtcars1["mpg"].max()-mtcars1["mpg"].min())
print("Range is \n",Range)

Range is
 23.5

### Question 7

Calculate the 25th quantile (lower quantile)for `mpg` in the given dataset.

**Hint:** Use **.quantile()**

In [98]:
Quantile=mtcars["mpg"].quantile()
print(Quantile)

19.2

### Question 8

Calculate the Inter-Quartile Range(IQR) for `mpg` in the given dataset.

Interquartile range (IQR) is another common measure of spread. IQR is the distance between the 3rd quartile and the 1st quartile.

**Hint:** IQR = Q3 - Q1

### Question 9

Calculate the Variance, Standard Deviation and Median Absolute Deviation for `mpg`.

Variance and Standard Deviation are two other common measure of dispersion.

**Hint:** Use .var() and .std()

**Hint:** Median Absolute Deviation - alternative measure of spread based on the median. It is the median of the absolute value of the deviations from the median.

In [92]:
print("Standard Deviation\n\b",mtcars["mpg"].std())
print("Variance \n\b",mtcars["mpg"].var())

Standard Deviation
 6.026948052089105
Variance
 36.32410282258065